functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность изменять количество товаров в корзине
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки

non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен обеспечивать бесперебойную работу при пиковой нагрузке
  - Сайт должен обеспечивать корректную работу при медленном интернете

implicit:
  - Добавленные товары должны сохраняться при обновлении страницы
  - При смене языка весь интерфейс и данные должны переводиться полностью
  - Сайт должен корректно отображаться и на компьютере, и на телефоне
  - Число товаров в корзине (в шапке) должно меняться сразу после добавления/удаления
  - Пользователь не может добавить в корзину больше единиц товара, чем доступно в наличии
  - При отсутствии товаров по запросу поиска/фильтрации должен отображаться информативный результат (например, сообщение «товары не найдены»)
  - При ошибках (например, сбой сети или проблемы с сервером) пользователю должны отображаться понятные сообщения об ошибке
  - Корзина и выбранный язык интерфейса должны сохраняться при повторном входе (например, через cookie или локальное хранилище)
